### ISSUE TITLE
ImmutableRecord could cache its hash value

### ISSUE THREAD

**Issue by dokempf** [inducer/pytools#13]
I was benchmarking my applications lately, and it turns out that I am using memoization and record-like data structures to an extent, where I spend a substantial amount of time evaluating the builtin `hash` function for `ImmutableRecord`. I first seeked for faster non-cryptographic hash implementations, but these suffer from the fact they only work on bytes objects, which moves the bottleneck to builtin `repr`. As an alternative, `ImmutableRecord` can cache it's hash value on first evaluation. This solves my original issue, but it is technically violating the data structures immutability (though only for the sake of an implementation detail). If you are interested, I provide a PR. If you're scared, I will just monkeypatch it in for my code...

**Comment by inducer** [comment]
As I mentioned in person today, I think that would be great to have. Added you to the project on Gitlab.

**Comment by matthiasdiener** [comment]
It looks like this was implemented in https://github.com/inducer/pytools/commit/4e4a925f0b63de1a45905447be043ef30b86adcb.
