### ISSUE TITLE
'NoneType' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by xywei** [inducer/pytools#15]
When I run commands in the interactive shell of `pudb`, `sys.stdin` is `None`. Thus the following line in `__init__.py` makes it impossible to call certain commands within `pudb` (e.g., `wrangler.translate_box_multipoles_to_qbx_local(mpole_exps)) ` from `pytential`).
```
use_late_start_logging = sys.stdin.isatty()   
```

I am happy to submit a patch if this is intended to be fixed.

**Comment by inducer** [comment]
Yup, please do submit a patch!

**Comment by xywei** [comment]
I am closing this since the original issue has been fixed.
