### ISSUE TITLE
Missing git tag (and tests in sdist) for 2024.1

### ISSUE THREAD

**Issue by mgorny** [inducer/pytools#203]
There is no tag on GitHub for 2024.1 release, and the sdist tarball on PyPI does not include tests. We really need *some* testable archive for Gentoo packaging. Please either push the tag or fix the sdist tarball to include tests again.

**Comment by inducer** [comment]
I thoroughly botched the release process for 2024.1. I've yanked that from the package index. 2024.1.1 is out, which, hopefully, should be all better.
