### ISSUE TITLE
PersistentDict: multithread support?

### ISSUE THREAD

**Issue by matthiasdiener** [inducer/pytools#233]
See e.g. https://gitlab.tiker.net/inducer/pyopencl/-/jobs/703834:

```
Exception ignored in: <function _PersistentDictBase.__del__ at 0x7fe3a0ff7ce0>
Traceback (most recent call last):
  File "/builds/inducer/pyopencl/boxtree/.conda-root/envs/testing/lib/python3.11/site-packages/pytools/persistent_dict.py", line 506, in __del__
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140615692060352 and this is thread id 140615717181248.
```

To reproduce in boxtree:

```console
$ pytest -n 4 test/test_tools.py
```

**Comment by inducer** [comment]
Thanks for spotting that! I had seen it fly by, but then lost track of the CI run where it happened. I'm not quite sure either why it's happening (there should only be a single thread?), or what to do about it. What's your take?

**Comment by inducer** [comment]
Also: this doesn't seem severe enough (yet?) to merit a yank, at least until we understand it better.

**Comment by vincefn** [comment]
Hi @matthiasdiener @inducer - I just hit this bug yesterday using pyopencl in a multi-threaded environment (old code, now I'm more relying on multiprocessing but the code still works so...).

What is strange is that it [fails in one of my CI pipelines](https://gitlab.esrf.fr/favre/PyNX/-/jobs/1099410), but when I run the same testsuite from my account with the same environment setup (and same computer), it passes. I don't know how the type of account can affect the caching mechanism ?

I [just confirmed](https://gitlab.esrf.fr/favre/PyNX/-/jobs/1101359) that if I revert to pytools 2024.1.3 and pyopencl 2024.2.5, this CI failure disappears in my tests...

**Comment by vincefn** [comment]
Followup - I just test this using a terminal in a remote desktop (so, _not a login shell_) and I could reproduce the issue. So that may explaine the difference between a CI job and a test in a login shell. Nasty.

**Comment by matthiasdiener** [comment]
Thanks for the infos @inducer @vincefn. I'm currently working on a solution similar to https://ricardoanderegg.com/posts/python-sqlite-thread-safety/, since most sqlite builds should be threadsafe already, it is the Python layer that does the thread-related extra check that fails.

**Comment by EdgarGF93** [comment]
Just to note that we have this issue with the package pyFAI while using pytools 2024.1.5, but it works with 2024.1.13

**Comment by inducer** [comment]
Thanks for letting us know. In your view, is there any action required at this point? I'll close this for now, but feel free to speak up if any of you thinks this is still an issue.

**Comment by EdgarGF93** [comment]
Thanks, I think there is no need of further action, but now we are aware if someone reports it
