### ISSUE TITLE
pytools==2020.3 is not compatible with Python 3.5 but it still got installed by pip

### ISSUE THREAD

**Issue by mutongx** [inducer/pytools#26]
Hi,

I noticed that `pytools` dropped its support for Python 3.5 in d125d07506d78366e67a6a377ae95bab8a14e320. However when I tried to install `pycuda` in a clean Ubuntu 16.04 environment, `pip` fetches `pytools=2020.3` for me. Calling import on pytools gives a syntax error.

According to https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires, should we add a `python_required` field to `setup.py` to prevent new versions from being installed under Python 3.5 environment?

Thanks!

**Comment by inducer** [comment]
Thanks for reporting this, and for teaching me about `python_required`! I think it would make sense for me to withdraw pytools 2020.3 and release 2020.3.1 with this declaration added. The same thing probably goes for pyopencl 2020.2. I'll do that first thing tomorrow morning.

**Comment by inducer** [comment]
Thanks again for the report. I've "yanked" 2020.3 on the package index and released 2020.3.1, hopefully with an appropriate Python version declaration.

Please comment/reopen if this is not resolved.
