### ISSUE TITLE
#46 broke the loopy CI

### ISSUE THREAD

**Issue by inducer** [inducer/pytools#47]
https://github.com/inducer/loopy/runs/1270140144

cc @kaushikcfd

**Comment by inducer** [comment]
I might just revert it for now.

**Comment by kaushikcfd** [comment]
It's picking up the wrong pytools version. (Confirmed on a local branch)

**Comment by kaushikcfd** [comment]
The PR actually fixes it.

**Comment by inducer** [comment]
Huh, OK. I guess I'm releasing another pytools tonight.

**Comment by inducer** [comment]
Thanks for looking into it, and sorry about incorrectly pointing fingers!

**Comment by inducer** [comment]
https://pypi.org/project/pytools/2020.4.3/

We'll need to wait for conda-forge to pick this up...

**Comment by kaushikcfd** [comment]
No problem.  And thanks for the version bump, needed it to pass some tests at other PRs.

**Comment by kaushikcfd** [comment]
Version bump [solved](https://github.com/inducer/loopy/runs/1271612497) the issue. (Thanks!). Could be closed now.

**Comment by inducer** [comment]
https://github.com/inducer/loopy/runs/1271655434

Looks like it's OK now. Thanks for your help!
