### ISSUE TITLE
pyopencl  issues with numpy >= 1.20.0

### ISSUE THREAD

**Issue by pierrepaleo** [inducer/pytools#54]
Numpy is preparing an [important release](https://numpy.org/devdocs/release/1.20.0-notes.html) which might deprecate/break  things.

In pyopencl, many tests fail with `numpy 1.20.0rc1`. Some minimal code to repoduce it:

```python
import numpy as np
import pyopencl as cl
import pyopencl.array as parray
ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)
d_data = parray.zeros(queue, (1,1), dtype=np.float32)
d_data += 1
```

which raises  
`TypeError: unsupported type for persistent hash keying: <class 'numpy.dtype[float32]'>`

The reason seems to be that the type name for such arrays changed:
  - with `numpy < 1.20.0rc1`: `type(np.array([1], dtype=np.float32).dtype).__name__` returns `'dtype'`
  - with `numpy >= 1.20.0rc1`: `type(np.array([1], dtype=np.float32).dtype).__name__` returns `'dtype[float32]'`

so `persistent_dict.KeyBuilder` class instance is not able to fetch the method `update_for_dtype()` anymore.

This dirty fix in `persistent_dict.KeyBuilder.rec()` seems to solve the issue:
```python
                # type_name = type(key).__name__ # previous - fails
                type_name = type(key).__name__.split("[")[0] # patch - works
                method = getattr(self, "update_for_"+type_name)
```
but I suspect there might be more elegant.

**Comment by inducer** [comment]
Thanks for the report! See #55 for my idea on how to address this.
