### ISSUE TITLE
bug in generate_all_nonnegative_integer_tuples

### ISSUE THREAD

**Issue by fenom** [inducer/pytools#89]
https://github.com/inducer/pytools/blob/a055fa845ada289809d450965cd323f337425fd5/pytools/__init__.py#L1444
`current_max` should be in a tuple, not a list.

**Comment by inducer** [comment]
Thanks for the report. I tried to fix this and add a test, but I found out that the algorithm used by the function was also broken. And, as you point out, the thing wasn't working to start with (so there's no backward compatibility issue with existing users), so in #90, I'm simply dropping this functionality.
